config/routes.rb
Rails.application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :children do
    member do
      put :color_up
      put :color_down
      post :redeem_screentime
    end
    collection do
      post :daily_reset_and_distribution
    end
  end

  resource :money_pool do
    post :adjust_current_balance_cents
    post :manual_adjust_current_balance_cents
  end

  root 'children#index'

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/child.rb
class Child < ApplicationRecord
  validates :name, presence:  true,
                   length:    {minimum: 2}

  enum color: [ :red, :orange, :yellow, :green, :blue, :purple ]

# back-end 'screentime' is now 'points' in the UI

  def self.daily_reset_and_distribution

    Child.all.each do |child|
      case child.color
        when 'red'
          # MoneyPool.adjust_current_balance_cents -75
        when 'orange'
          child.screentime += 1    # points
          # MoneyPool.adjust_current_balance_cents -50
        when 'yellow'
          child.screentime += 2    # points
          # MoneyPool.adjust_current_balance_cents -25
        when 'green'
          child.screentime += 3    # points
          # MoneyPool.adjust_current_balance_cents 25
        # when 'pink'
          # child.screentime += 10
          # MoneyPool.adjust_current_balance_cents 50
        when 'blue'
          child.screentime += 4    # points
          # MoneyPool.adjust_current_balance_cents 75
        when 'purple'
          child.screentime += 5    # points
          # MoneyPool.adjust_current_balance_cents 100
      end

      child.color = 'red'
      child.save
    end
  end

end

app/models/money_pool.rb
class MoneyPool < ApplicationRecord
  def self.money_pool
    @money_pool ||= MoneyPool.find_or_create_by(id: 1)
  end

  validates_inclusion_of :id, in: [1] # Only allow one

  def self.current_balance_in_cents
    money_pool.current_balance_in_cents
  end

  def self.current_balance
    current_balance_in_cents.to_f / 100
  end

  def self.adjust_current_balance_cents(value)
    money_pool.current_balance_in_cents += value
    money_pool.save
  end

  def self.manual_adjust_current_balance_cents(value)
    @value = value.to_f
    @amount_to_add_in_cents = @value * 100
    money_pool.current_balance_in_cents += @amount_to_add_in_cents.to_i
    money_pool.save
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authorize

  protected

  def authorize
    unless User.find_by(id: session[:user_id])
      redirect_to login_url, notice: 'Please log in.'
    end
  end
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  def index
    @children = Child.all
  end

  def show
    @child = Child.find(params[:id])
  end

  def new
    @child = Child.new
  end

  def edit
    @child = Child.find(params[:id])
  end

  def create
    @child = Child.new(child_params)

    if @child.save
      redirect_to @child
    else
      render 'new'
    end
  end

  def update
    @child = Child.find(params[:id])

    if @child.update(child_params)
      redirect_to @child
    else
      render 'edit'
    end
  end

  def destroy
    @child = Child.find(params[:id])
    @child.destroy

    redirect_to children_path
  end

  def color_up
    @child = Child.find(params[:id])
    unless Child.colors[@child.color] == 6
      @child.color = Child.colors[@child.color] + 1
      @child.save
    end

    redirect_to children_path
  end

  def color_down
    @child = Child.find(params[:id])
    unless Child.colors[@child.color] == 0
      @child.color = Child.colors[@child.color] - 1
      @child.save
    end

    redirect_to children_path
  end

  def redeem_screentime
    @child = Child.find(params[:id])
    @time_redeemed = params[:time_redeemed].to_i

    @child.screentime = @child.screentime - @time_redeemed
    @child.save

    redirect_to @child
  end

  def daily_reset_and_distribution
    Child.daily_reset_and_distribution

    redirect_to root_path
  end

  private

  def child_params
    params.require(:child).permit(:name, :goal, :color, :screentime)
    # back-end 'screentime' is now called 'points' in the UI
  end

end

app/controllers/money_pools_controller.rb
class MoneyPoolsController < ApplicationController
  def manual_adjust_current_balance_cents
   MoneyPool.manual_adjust_current_balance_cents(params[:value])

   redirect_to root_path
  end

  def show
    @money_pool = MoneyPool.find(1)
  end

  private

  def money_pool_params
    params.require(:money_pool).permit(:id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_url, alert: 'Invalid Login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, notice: 'Logged Out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html do
          redirect_to users_url,
          notice: "User #{@user.name} was successfully created."
        end
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html do
          redirect_to users_url,
          notice: "User #{@user.name} was successfully updated."
        end
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html do
        redirect_to users_url, notice: 'User was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/money_pool_helper.rb
module MoneyPoolHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/children/edit.html.erb
<div class="container-fluid form">

  <h1>Edit <%= @child.name %></h1>

  <%= form_for @child, method: :patch do |f| %>

  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@child.errors.count, "error") %> prevented this from saving
      </h2>
      <ul>
        <% @child.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <p>
      <%= f.label :goal, 'Goal' %><br>
      <%= f.text_area :goal %>
    </p>

    <p>
      <%= f.submit %>
    </p>

    <p>
      <%= link_to 'Cancel', children_path %>
    </p>

    <% end %>
</div>

app/views/children/index.html.erb
<div class="container-fluid pre-scrollable", id="content">
  <% @children.order(:name).each do |child| %>
    <div class="childbox <%= child.color %>">
      <div class="colored-row">
        <div class="col-xl-8">
          <h1 class="<%= child.color %>">
            <%= link_to "#{child.name}", child_path(child), class: child.color %>
            <div class="btn-group">
              <%= link_to color_up_child_path(child), class:'btn btn-default btn-lg',
                  method: :put do %>
                  <span class="glyphicon glyphicon-chevron-up"></span>
              <% end %>
              <%= link_to color_down_child_path(child), class:'btn btn-default btn-lg',
                  method: :put do %>
                  <span class="glyphicon glyphicon-chevron-down"></span>
              <% end %>
            </div>
          </h1>
          <p>
            <%= child.goal %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
  <br/>
  <div class="container-fluid">
    <%= link_to 'Add Child', new_child_path, class:'btn btn-block btn-lg btn-default' %>
  </div>
</div>

app/views/children/new.html.erb
<div class="container-fluid form">

  <h1>Add Child</h1>

  <%= form_for :child, url: children_path do |f| %>

    <% if @child.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@child.errors.count, "error") %> prevented this from saving
        </h2>
        <ul>
          <% @child.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.label :name, 'Name' %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :goal, 'Goal' %><br>
      <%= f.text_area :goal %>
    </p>
    <p>
      <%= f.submit %>
    </p>

    <p>
      <%= link_to 'Cancel', root_path %>
    </p>
  <% end %>
</div>

app/views/children/show.html.erb
<div class="container-fluid form">
  <h1><%= @child.name %>'s Status</h1>
  <p>Goal: <%= @child.goal %></p>
  <h3>Screentime: <%= @child.screentime %> minutes</h3>
  <div class="btn-group">
    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal2">Use Screentime</button>
    <!-- Modal -->
    <div class="modal fade" id="myModal2" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <%= form_with url: redeem_screentime_child_path, method: :post do |form| %>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">How much screentime was used?</h4>
          </div>
          <div class="modal-body">
              <%= form.number_field :time_redeemed %><p>minutes</p>
          </div>
          <div class="modal-footer">
            <div class="actions">
              <%= form.submit "Enter" %>
            </div>
          </div>
          <% end %>
        </div>

      </div>
    </div>
    <%= link_to 'Edit Goal', edit_child_path(@child), class: 'btn btn-default' %>
    <%= link_to 'Delete', @child, method: :delete,
        class: 'btn btn-default', data: {confirm: 'Are you sure?'} %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clipchart!</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to 'Clipchart!', root_path, class: "navbar navbar-brand" %>
        </div>
        <div class="container-fluid logout">
          <%= link_to 'Logout', logout_path, method: :delete %>
        </div>
      </div>
    </nav>

    <div class="container-fluid" id="content">
      <%= yield %>
    </div>
    
    <!-- Modal-->
    <div class="modal fade" id="myModal1" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content  -->
        <div class="modal-content">
          <%= form_with url: manual_adjust_current_balance_cents_money_pool_path,
              method: :post do |form| %>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Adjust balance by how much?</h4>
          </div>
          <div class="modal-body">
              <%= form.text_field :value %>
              <p>Use a - for debits</p>
          </div>
          <div class="modal-footer">
            <div class="actions">
              <%= form.submit "Enter" %>
            </div>
          </div>
          <% end %>
        </div>

      </div>
    </div>

    <footer class="footer text-center">
      <div class="button-group">

        <%= link_to 'Daily Reset', daily_reset_and_distribution_children_path, method: :post,
            class: 'btn btn-default btn-lg',
            data: {confirm: "Distribute awards and reset all children to green?"} %>
        <button type="button" class='btn btn-default btn-lg' data-toggle="modal" data-target="#myModal1">
          <%= "Money Pool: #{number_to_currency(MoneyPool.current_balance)}" %>
        </button>

      </div>
    </footer>

  </body>

</html>

app/views/money_pools/show.html.erb
<h1>Spend From Money Pool</h1>
</br>
<h3>
  Current Balance: <%= number_to_currency(MoneyPool.current_balance) %>
</h3>

<%= form_with url: manual_adjust_current_balance_cents_money_pool_path, method: :post do |form| %>
<p>
  <%= form.label :value, 'Change Balance by Value: ' %>
  <%= form.number_field :value %>
</p>

<p>
  <%= form.submit %>
</p>

<% end %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend>Enter User Details</legend>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>